[env:esp32s3_littlefs]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags =
    -Isrc
monitor_speed = 115200

[env:esp32s3_spiffs]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags =
    -Isrc
monitor_speed = 115200

[env:esp32_littlefs]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -DUSE_LITTLEFS
    -Isrc
monitor_speed = 115200

[env:esp32_spiffs]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -Isrc
monitor_speed = 115200

[env:esp8266_littlefs]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags =
    -DUSE_LITTLEFS
    -Isrc
monitor_speed = 115200

[env:esp8266_spiffs]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags =
    -Isrc
monitor_speed = 115200